# This is a basic workflow to help you get started with Actions

name: deploy-full-blue-green
# https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#workflow_run
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
    paths:
      - apps/js-calc-backend/**
      - apps/js-calc-frontend/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

defaults:
  run:
    working-directory: apps

env:
  BACKEND_APP_NAME: js-calc-backend
  FRONTEND_APP_NAME: js-calc-frontend

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy_ota:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
    - uses: actions/checkout@v2

    - name: Build image
      run: |
        docker build . --file $BACKEND_APP_NAME/Dockerfile --tag $BACKEND_APP_NAME --label "runnumber=${GITHUB_RUN_ID}"
        docker build . --file $FRONTEND_APP_NAME/Dockerfile --tag $FRONTEND_APP_NAME --label "runnumber=${GITHUB_RUN_ID}"

    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push image
      run: |
        BACKEND_IMAGE_ID=ghcr.io/${{ github.repository_owner }}/container-apps/$IMAGE_NAME
        # Change all uppercase to lowercase
        BACKEND_IMAGE_ID=$(echo $BACKEND_IMAGE_ID | tr '[A-Z]' '[a-z]')
        # Strip git ref prefix from version
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        # Strip "v" prefix from tag name
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        # Use Docker `latest` tag convention
        [ "$VERSION" == "master" ] && VERSION=latest
        echo BACKEND_IMAGE_ID=$BACKEND_IMAGE_ID
        echo VERSION=$VERSION
        docker tag $BACKEND_APP_NAME $BACKEND_IMAGE_ID:$VERSION
        docker push $BACKEND_IMAGE_ID:$VERSION

        FRONDEND_IMAGE_ID=ghcr.io/${{ github.repository_owner }}/container-apps/$IMAGE_NAME
        # Change all uppercase to lowercase
        FRONDEND_IMAGE_ID=$(echo $FRONDEND_IMAGE_ID | tr '[A-Z]' '[a-z]')
        # Strip git ref prefix from version
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        # Strip "v" prefix from tag name
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        # Use Docker `latest` tag convention
        [ "$VERSION" == "master" ] && VERSION=latest
        echo FRONDEND_IMAGE_ID=$FRONDEND_IMAGE_ID
        echo VERSION=$VERSION
        docker tag $FRONTEND_APP_NAME $FRONDEND_IMAGE_ID:$VERSION
        docker push $FRONDEND_IMAGE_ID:$VERSION

    - name: Install CLI-beta
      run: |
        cd ../..
        CWD="$(pwd)"
        python3 -m venv oidc-venv
        . oidc-venv/bin/activate
        echo "activated environment" 
        python3 -m pip install --upgrade pip
        echo "started installing cli beta" 
        pip install -q --extra-index-url https://azcliprod.blob.core.windows.net/beta/simple/ azure-cli
        echo "installed cli beta"    
        echo "$CWD/oidc-venv/bin" >> $GITHUB_PATH

    # Login to Azure 
    - name: Azure Login Xpirit
      uses: azure/login@v1.4.0
      with:
        client-id: ${{ secrets.AZURE_CLIENTID }}
        tenant-id: ${{ secrets.AZURE_TENANTID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTIONID }}

    - name: 'Run az commands'
      run: |
        az group create -l westeurope -n rg-d